#!/bin/bash

# =================================================================
#
# Copyright (C) 2020 Spatial Current, Inc. - All Rights Reserved
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

XC_OS=${1:-linux darwin windows}
XC_ARCH=${2:-386 amd64 arm arm64}
XC_EXCLUDE_OSARCH="!darwin/arm !darwin/arm64 !darwin/386"

export CGO_ENABLED=0

export GOFLAGS="-mod=readonly"

export GOPATH=${GOPATH:-$(go env GOPATH)}

go mod download

${DIR}/../bin/gox \
-os="${XC_OS}" \
-arch="${XC_ARCH}" \
-osarch="${XC_EXCLUDE_OSARCH}" \
-ldflags "-s -w" \
-output "bin/{{.Dir}}_{{.OS}}_{{.Arch}}" \
github.com/spatialcurrent/gosync/cmd/gosync
